<?php
/**
 * Show most popular product by likes
 *
 */

?>

<?php $_products = $this->getProducts();?>

<div class="widget widget-new-products">
    <div class="block block-products">
        <div class="block-title">
            <strong><span><?php echo $this->getData('likes_title'); ?></span></strong>
        </div>
        <div class="block-content">
            <?php echo $this->getPagerHtml() ?>
            <?php $suffix = $this->getNameInLayout(); ?>
            <ol class="mini-products-list" id="widget-new-products-<?php echo $suffix; ?>">
                <?php foreach ($_products as $_product): ?>
                    <li class="popular-products-widget item">
                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(50) ?>" width="50" height="50" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                        <div class="product-details">
                            <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
                            <?php echo $this->getPriceHtml($_product, true, '-widget-new-'.$suffix) ?>
                            <p id="likes_text"><?php echo $this->__('Likes').':';?><?php echo $_product['like_count'];?></p>
<!--                            block "add to cart"-->
                            <?php if ($_product->getIsSalable()): ?>
                                <a href="<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>" class="link-cart"><?php echo $this->__('Add to Cart') ?></a>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('widget-new-products-<?php echo $suffix; ?>', 'none-recursive')</script>
        </div>
    </div>
</div>
